services:
  serveradministrator:
    build: ./testOrchestrator/services/serverAdministrator
    container_name: serverAdministrator_v2
    ports:
      - "5000:5000"
    image: production-serveradministrator-latest
    expose: # Usa 'expose' para puertos internos entre contenedores en la misma red
      - "5000" # El puerto 5000 del contenedor es accesible por otros servicios en 'app_network'
    restart: always
    hostname: serverAdministrator
    networks:
      - my_shared_network

  users:
    build: ./testOrchestrator/services/users
    container_name: users_v2
    ports:
      - "5001:5000"
    image: production-users-latest
    expose:
      - "5001"
    restart: always
    hostname: users
    networks:
      - my_shared_network

  orchestrator:
    build: ./testOrchestrator/services/orchestrator
    container_name: orchestrator_v2
    ports:
      - "5002:5000"
    image: production-orchestrator-latest
    expose:
      - "5002"
    restart: always
    hostname: orchestrator
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true # Declares that this network already exists and was created externally
    name: my_shared_network # The actual name of the network you created with `docker network create`